// <auto-generated />
using Labb3_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb3_API.Migrations
{
    [DbContext(typeof(InterestDbContext))]
    [Migration("20260422123417_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterestUser", b =>
                {
                    b.Property<int>("InterestsId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("InterestsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("InterestUser");
                });

            modelBuilder.Entity("Labb3_API.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Att skriva kod och utveckla applikationer",
                            Name = "Programmering"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fysisk aktivitet som gym, löpning eller sport",
                            Name = "Träning"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lyssna på eller skapa musik",
                            Name = "Musik"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Utforska nya platser och kulturer",
                            Name = "Resor"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Laga och experimentera med mat",
                            Name = "Matlagning"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Spela dator- eller tv-spel",
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Läsa böcker, artiklar eller annan litteratur",
                            Name = "Läsning"
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("UserId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 1,
                            Url = "https://github.com",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 3,
                            Url = "https://spotify.com",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 2,
                            Url = "https://gymshark.com",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            InterestId = 6,
                            Url = "https://twitch.tv",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            InterestId = 4,
                            Url = "https://tripadvisor.com",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            InterestId = 5,
                            Url = "https://foodblog.com",
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            InterestId = 7,
                            Url = "https://goodreads.com",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "anna.svensson@gmail.com",
                            FullName = "Anna Svensson",
                            Phone = "0701234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "erik.johansson@hotmail.com",
                            FullName = "Erik Johansson",
                            Phone = "0729876543"
                        },
                        new
                        {
                            Id = 3,
                            Email = "sara.andersson@gmail.com",
                            FullName = "Sara Andersson",
                            Phone = "0731122334"
                        });
                });

            modelBuilder.Entity("InterestUser", b =>
                {
                    b.HasOne("Labb3_API.Models.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb3_API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Labb3_API.Models.Link", b =>
                {
                    b.HasOne("Labb3_API.Models.Interest", "Interest")
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb3_API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
