// <auto-generated />
using Labb3_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb3_API.Migrations
{
    [DbContext(typeof(InterestDbContext))]
    [Migration("20260427090348_createdNewTable")]
    partial class createdNewTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb3_API.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Att skriva kod och utveckla applikationer",
                            Title = "Programmering"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fysisk aktivitet som gym, löpning eller sport",
                            Title = "Träning"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lyssna på eller skapa musik",
                            Title = "Musik"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Utforska nya platser och kulturer",
                            Title = "Resor"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Laga och experimentera med mat",
                            Title = "Matlagning"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Spela dator- eller tv-spel",
                            Title = "Gaming"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Läsa böcker, artiklar eller annan litteratur",
                            Title = "Läsning"
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserInterestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserInterestId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("Labb3_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "anna.svensson@gmail.com",
                            FullName = "Anna Svensson",
                            Phone = "0701234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "erik.johansson@hotmail.com",
                            FullName = "Erik Johansson",
                            Phone = "0729876543"
                        },
                        new
                        {
                            Id = 3,
                            Email = "sara.andersson@gmail.com",
                            FullName = "Sara Andersson",
                            Phone = "0731122334"
                        },
                        new
                        {
                            Id = 4,
                            Email = "johan.nilsson@gmail.com",
                            FullName = "Johan Nilsson",
                            Phone = "0704455667"
                        },
                        new
                        {
                            Id = 5,
                            Email = "emma.karlsson@hotmail.com",
                            FullName = "Emma Karlsson",
                            Phone = "0723344556"
                        },
                        new
                        {
                            Id = 6,
                            Email = "lucas.berg@gmail.com",
                            FullName = "Lucas Berg",
                            Phone = "0735566778"
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.UserInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("UserId");

                    b.ToTable("UserInterest");
                });

            modelBuilder.Entity("Labb3_API.Models.Link", b =>
                {
                    b.HasOne("Labb3_API.Models.UserInterest", "UserInterest")
                        .WithMany("Links")
                        .HasForeignKey("UserInterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInterest");
                });

            modelBuilder.Entity("Labb3_API.Models.UserInterest", b =>
                {
                    b.HasOne("Labb3_API.Models.Interest", "Interests")
                        .WithMany("UserInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb3_API.Models.User", "User")
                        .WithMany("UnserInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interests");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Labb3_API.Models.Interest", b =>
                {
                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("Labb3_API.Models.User", b =>
                {
                    b.Navigation("UnserInterests");
                });

            modelBuilder.Entity("Labb3_API.Models.UserInterest", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
